# A network of four nodes connected in a line that connects Alice to Bob, Bob to Charlie and Charlie to David.
# This network configuration has no noise.
generic_qdevice_cfg: &generic_qdevice_cfg
    num_qubits: 2
    # coherence times (The value 0 disables decoherence)
    T1: 500_000_000
    T2: 500_000_000

    # gate execution times
    init_time: 0.00001
    single_qubit_gate_time: 0.00001
    two_qubit_gate_time: 0.00001
    measure_time: 0.00001

    # noise model
    single_qubit_gate_depolar_prob: 0.05
    two_qubit_gate_depolar_prob: 0.05

stacks:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *generic_qdevice_cfg
  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *generic_qdevice_cfg
  - name: Charlie
    qdevice_typ: generic
    qdevice_cfg:
      <<: *generic_qdevice_cfg
  - name: David
    qdevice_typ: generic
    qdevice_cfg:
      <<: *generic_qdevice_cfg

links:
  - stack1: Alice
    stack2: Bob
    typ: depolarise
    cfg:
      fidelity: 0.97
      t_cycle: 0.1
      prob_success: 0.2

  - stack1: Bob
    stack2: Charlie
    typ: depolarise
    cfg:
      fidelity: 0.97
      t_cycle: 0.1
      prob_success: 0.2

  - stack1: Charlie
    stack2: David
    typ: depolarise
    cfg:
      fidelity: 0.97
      t_cycle: 0.1
      prob_success: 0.2


clinks:
  - stack1: Alice
    stack2: Bob
    typ: default
    cfg:
      delay: 0.05

  - stack1: Bob
    stack2: Charlie
    typ: default
    cfg:
      delay: 0.05

  - stack1: Charlie
    stack2: David
    typ: default
    cfg:
      delay: 0.05